### ISSUE TITLE
V2 initial todo list

### ISSUE THREAD

**Issue by cookie777** [cookie777/Hang-Out-Planner#55]
- [x] change to diffable datacourse
- [x] change to collection view compositional layout
- [x] refactor
  - [x] indenfier
  - [ ] array -> set (location) to make O(1) find
  - [x] pass location , not id
  - [x] avoid global vars and move to `Constants` or `shared`
- [x]  check mark in category cell
- [x]  organize controller (network, location manager)
